aws_region           = "eu-north-1"
environment          = "dev"
project_name         = "bedrock-ai"
vpc_cidr             = "10.0.0.0/16"
public_subnet_1_cidr = "10.0.1.0/24"
public_subnet_2_cidr = "10.0.2.0/24"
az_1                 = "eu-north-1a"
az_2                 = "eu-north-1b"